---
version: 2

jobs:
  "linkcheck":
    docker:
        - image: testthedocs/cci-linkcheck:0.0.2
    steps:
      - checkout
      - run:
          command: |
            su-exec ttd /usr/local/bin/linkcheck -c '200,301,302' -t 5 docs

  "hadolint":
    docker:
      - image: hadolint/hadolint:latest-debian
    steps:
      - checkout
      - run: hadolint --ignore DL3018 checks/linkcheck/Dockerfile
      - run: hadolint --ignore DL3018 checks/remark/Dockerfile

workflows:
  version: 2
  btd:
    jobs:
      - "linkcheck"
      - "hadolint"
